import os
import shlex

from kittens.tui.handler import result_handler

# Bare shells aren't worth re-launching explicitly (the session's default
# shell already does that) — only relaunch a *foreground program* on top.
SHELL_NAMES = {"bash", "zsh", "fish", "sh", "dash", "ksh", "tcsh", "csh"}


def main(args: list[str]) -> None:
    pass


def _launch_line(window, home: str) -> str:
    """Build a `launch` line that restores cwd AND, if a real program
    (nvim, claude, htop, ...) was running in foreground, re-runs it.
    Note: this restarts the program fresh — it cannot restore its
    internal state (open buffers, scrollback, shell history).
    """
    cwd = window.cwd_of_child or home
    parts = [f"launch --cwd {shlex.quote(cwd)}"]
    try:
        cmd = list(window.child.foreground_cmdline or [])
    except Exception:
        cmd = []
    if cmd and os.path.basename(cmd[0]) not in SHELL_NAMES:
        # --hold: keep the tab if the relaunched program exits/crashes,
        # instead of it silently vanishing.
        parts.append("--hold")
        parts.append(" ".join(shlex.quote(c) for c in cmd))
    return " ".join(parts)


def _write_session(boss) -> None:
    """Snapshot the current OS window's tabs/layout/cwd/foreground-program
    to session.conf. Mirrors save_session.py (kept standalone so kitten
    imports stay simple).
    """
    session_path = os.path.expanduser("~/.config/kitty/session.conf")
    home = os.path.expanduser("~")
    tm = boss.active_tab_manager
    if tm is None:
        return
    lines = [
        "# kitty session (resurrect target)",
        "# Auto-generated by ctrl+space>q>q (save_and_close.py).",
    ]
    for tab in tm.tabs:
        lines.append(f"new_tab {tab.name or ''}".rstrip())
        lines.append(f"layout {tab.current_layout.name}")
        for window in tab.windows:
            lines.append(_launch_line(window, home))
    with open(session_path, "w") as f:
        f.write("\n".join(lines) + "\n")


@result_handler(no_ui=True)
def handle_result(args: list[str], answer, target_window_id: int, boss) -> None:
    """qq: save session, then close this OS window in one step."""
    _write_session(boss)
    boss.close_os_window()
