import os
import shlex

from kittens.tui.handler import result_handler

# Bare shells aren't worth re-launching explicitly (the session's default
# shell already does that) — only relaunch a *foreground program* on top.
SHELL_NAMES = {"bash", "zsh", "fish", "sh", "dash", "ksh", "tcsh", "csh"}


def main(args: list[str]) -> None:
    pass


def _launch_line(window, home: str) -> str:
    """Build a `launch` line that restores cwd AND, if a real program
    (nvim, claude, htop, ...) was running in foreground, re-runs it.
    Note: this restarts the program fresh — it cannot restore its
    internal state (open buffers, scrollback, shell history).
    """
    cwd = window.cwd_of_child or home
    parts = [f"launch --cwd {shlex.quote(cwd)}"]
    try:
        cmd = list(window.child.foreground_cmdline or [])
    except Exception:
        cmd = []
    if cmd and os.path.basename(cmd[0]) not in SHELL_NAMES:
        # --hold: keep the tab if the relaunched program exits/crashes,
        # instead of it silently vanishing.
        parts.append("--hold")
        parts.append(" ".join(shlex.quote(c) for c in cmd))
    return " ".join(parts)


@result_handler(no_ui=True)
def handle_result(args: list[str], answer, target_window_id: int, boss) -> None:
    """Dump the current OS window's tabs/windows to session.conf.

    Bound to ctrl+space>q>s. This is the 'resurrect' analog: kitty has no
    live-state autosave, so we snapshot layout + cwd + foreground program
    on demand into the file that `startup_session` loads on next launch.
    """
    session_path = os.path.expanduser("~/.config/kitty/session.conf")
    home = os.path.expanduser("~")

    tm = boss.active_tab_manager
    if tm is None:
        boss.show_error("Save session", "No active OS window to save.")
        return

    lines = [
        "# kitty session (resurrect target)",
        "# Auto-generated by ctrl+space>q>s (save_session.py).",
    ]
    for tab in tm.tabs:
        title = tab.name or ""
        lines.append(f"new_tab {title}".rstrip())
        lines.append(f"layout {tab.current_layout.name}")
        for window in tab.windows:
            lines.append(_launch_line(window, home))

    with open(session_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    boss.show_error("Save session", f"Wrote {session_path}")
